/****** Initial values *******/
const incomeField = document.querySelector('#income');
const foodField = document.querySelector('#food');
const rentField = document.querySelector('#rent');
const clothesField = document.querySelector('#clothes');
const saveField = document.querySelector('#save');
const balanceField = document.querySelector('#balance');
const calculateBtn = document.querySelector('#calculate-btn');
const btnSave = document.querySelector('#btn-save');
const errorMessage = document.querySelector('#error-message');
const saveError = document.querySelector('#save-error');
